from typing import Protocol

from aiogram.types import Message
from sqlalchemy.ext.asyncio import AsyncSession


class ICommandUseCase(Protocol):
    async def start(self, message: Message, session: AsyncSession): ...

    async def join(self, message: Message, session: AsyncSession): ...

    async def leave(self, message: Message, session: AsyncSession): ...


class ILogger(Protocol):
    def debug(self, message: str, *args, **kwargs) -> None: ...

    def info(self, message: str, *args, **kwargs) -> None: ...

    def warn(self, message: str, *args, **kwargs) -> None: ...

    def error(self, message: str, *args, **kwargs) -> None: ...
