"""edit telegram chat ids from varchar to bigint

Revision ID: df0f43073afb
Revises: 71c129cc19d6
Create Date: 2026-02-19 09:09:07.851574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'df0f43073afb'
down_revision: Union[str, None] = '71c129cc19d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'group_id',
                    existing_type=sa.VARCHAR(length=30),
                    type_=sa.BigInteger(),
                    existing_nullable=False,
                    postgresql_using='group_id::bigint')
    op.alter_column('users', 'chat_id',
                    existing_type=sa.VARCHAR(length=30),
                    type_=sa.BigInteger(),
                    existing_nullable=False,
                    postgresql_using='chat_id::bigint')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'chat_id',
                    existing_type=sa.BigInteger(),
                    type_=sa.VARCHAR(length=30),
                    existing_nullable=False)
    op.alter_column('groups', 'group_id',
                    existing_type=sa.BigInteger(),
                    type_=sa.VARCHAR(length=30),
                    existing_nullable=False)
    # ### end Alembic commands ###
